# Generated by Django 5.0 on 2026-01-04 05:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Breve descripción del gasto', max_length=200, verbose_name='título')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del gasto en pesos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='monto')),
                ('category', models.CharField(choices=[('GROCERIES', 'Comestibles'), ('LEISURE', 'Entretenimiento'), ('ELECTRONICS', 'Electrónicos'), ('UTILITIES', 'Servicios Públicos'), ('CLOTHING', 'Ropa'), ('HEALTH', 'Salud'), ('OTHERS', 'Otros')], help_text='Categoría del gasto', max_length=20, verbose_name='categoría')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del gasto (opcional)', null=True, verbose_name='descripción')),
                ('date', models.DateField(help_text='Fecha en que se realizó el gasto', verbose_name='fecha del gasto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='expenses_user_id_513cb5_idx'), models.Index(fields=['category'], name='expenses_categor_a6f264_idx'), models.Index(fields=['date'], name='expenses_date_a77b87_idx'), models.Index(fields=['-date'], name='expenses_date_61c88d_idx')],
            },
        ),
    ]
